### ISSUE TITLE
NetWrapper Cleanup

### ISSUE THREAD

**Issue by AnchyDev** [LoneDev6/Craftopia-DiscordRichPresence#4]
You have a singleton available for accessing the player, you can access it by calling:
```cs
OcPlMaster.Inst.PlLevelCtrl
```
instead of 
```cs
SingletonMonoBehaviour<OcNetMng>.FindObjectOfType<OcPl>().PlLevelCtrl
```

You also have two null checks on the variable _player_ inside of _PlayerNextLevelExp_

**Comment by LoneDev6** [comment]
I need more sleep 🤣
